server:
  port: ${PORT}

ead:
  serviceRegistry:
    username: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80