#server:
#  port: 8083
#  servlet:
#    context-path: /ead-notification

spring:
  application:
    name: ead-notification-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
#  datasource:
#    url:  jdbc:postgresql://localhost:5432/ead-notification
#    username: postgresuser
#    password: postgrespwd
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#    ansi:
#      enabled: ALWAYS
#  rabbitmq:
#    addresses: amqps://mtihecdc:z2qjgj7BT86LR9xlYUm4cTjHbTeckseh@woodpecker.rmq.cloudamqp.com/mtihecdc
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#ead:
#  broker:
#    exchange:
#      notificationCommandExchange: ead.notificationcommand
#    queue:
#      notificationCommandQueue:
#        name: ead.notificationcommand.ms.notification
#    key:
#      notificationCommandKey: ms.notification
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - refresh
#          - health
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost
