spring:
  output:
    ansi:
      enabled: always
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: configserver
      password: 'ead123cs'
