server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PauloPimentel-github/ead-config-server-repo
          default-label: main
          username: PauloPimentel-github
          password: '{cipher}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'
  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost